// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvN_BefDcjhySkk5NlOYNBUv6QdlPYkZY',
    appId: '1:204333446761:web:ebb12e60325759cf1fd4f8',
    messagingSenderId: '204333446761',
    projectId: 'smart-home-fc045',
    authDomain: 'smart-home-fc045.firebaseapp.com',
    storageBucket: 'smart-home-fc045.firebasestorage.app',
    measurementId: 'G-QH69L46D48',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHI2a0MMRJzs7Ah8x1QX-udvkXcmoMc3o',
    appId: '1:204333446761:android:7f8d725384b6cfdf1fd4f8',
    messagingSenderId: '204333446761',
    projectId: 'smart-home-fc045',
    storageBucket: 'smart-home-fc045.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjp01iSIV7plYy5vzpX75XJQshmOCFHYg',
    appId: '1:204333446761:ios:65e61100f7749d381fd4f8',
    messagingSenderId: '204333446761',
    projectId: 'smart-home-fc045',
    storageBucket: 'smart-home-fc045.firebasestorage.app',
    iosBundleId: 'com.example.smarthomeAppUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjp01iSIV7plYy5vzpX75XJQshmOCFHYg',
    appId: '1:204333446761:ios:65e61100f7749d381fd4f8',
    messagingSenderId: '204333446761',
    projectId: 'smart-home-fc045',
    storageBucket: 'smart-home-fc045.firebasestorage.app',
    iosBundleId: 'com.example.smarthomeAppUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvN_BefDcjhySkk5NlOYNBUv6QdlPYkZY',
    appId: '1:204333446761:web:10f32184a0ba9ae91fd4f8',
    messagingSenderId: '204333446761',
    projectId: 'smart-home-fc045',
    authDomain: 'smart-home-fc045.firebaseapp.com',
    storageBucket: 'smart-home-fc045.firebasestorage.app',
    measurementId: 'G-YDF3GE8C8W',
  );
}
